# Use container-based infrastructure
sudo: false

language: python

python:
  - 3.5

env:
  - CONDA_PACKAGES="numpy scipy matplotlib pandas"

before_install:
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - export CONDA_GREP="$(echo $CONDA_PACKAGES | sed 's/ /\\|/g')"

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  # Get conda requirements, without minor version numbers
  - cat requirements.txt | grep "$CONDA_GREP" | sed 's/\([0-9]\+\.[0-9]\+\)\.[0-9]\+$/\1/' | sed 's/==/=/' | xargs conda install --yes
  - conda install --yes pip
  # Get remaining pip requirements
  - cat requirements.txt | grep -v "$CONDA_GREP" | xargs pip install

script:
  - py.test
