# Use container-based infrastructure
sudo: false

language: python

python:
  - 3.5

before_install:
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes --file requirements_conda.txt
  - conda install pip
  - pip install -r requirements_pip.txt

script:
  - py.test
