# Use container-based infrastructure
sudo: false

language: python

python:
  - 3.5

addons:
  postgresql: 9.4

services:
  - postgresql

env:
  - CONDA_PACKAGES="numpy scipy matplotlib pandas pyzmq"

before_install:
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - export CONDA_GREP="$(echo $CONDA_PACKAGES | sed 's/ /\\|/g')"

install:
  - bash install_treetagger.sh
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  # Until conda can handle setuptools requirements.txt (https://github.com/conda/conda-env/pull/172), we separate conda and pip requirements
  # Get conda requirements, without minor version numbers
  - cat requirements.txt | grep "$CONDA_GREP" | sed 's/\([0-9]\+\.[0-9]\+\)\.[0-9]\+$/\1/' | sed 's/==/=/' | xargs conda install --yes
  - conda install --yes pip
  # Get remaining pip requirements
  - cat requirements.txt | grep -v "$CONDA_GREP" | xargs pip install
  # Install necessary datasets now that we have all dependencies
  - bash install_datasets.sh
  # FIXME: get a real package working instead of this
  - pip install --editable .

before_script:
  - psql -c 'create database brainscopypaste_test;' -U postgres
  - psql -c 'create user brainscopypaste;' -U postgres
  - psql -c 'alter database brainscopypaste_test owner to brainscopypaste;' -U postgres

script:
  - py.test
